"""Add stored_filename field to book schema.

Revision ID: 16caea5965e2
Revises: dcfff0dbc04d
Create Date: 2025-06-14 01:12:14.378562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16caea5965e2'
down_revision: Union[str, None] = 'dcfff0dbc04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stored_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'stored_filename')
    # ### end Alembic commands ###
