"""Add 'file_size_bytes' to books table.

Revision ID: 47c4e65fca3b
Revises: 9d6109349e1e
Create Date: 2025-06-09 22:17:55.255303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c4e65fca3b'
down_revision: Union[str, None] = '9d6109349e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'file_size_bytes')
    # ### end Alembic commands ###
