"""Update books schema fields.

Revision ID: 9d6109349e1e
Revises: 999ccf5cba3b
Create Date: 2025-06-09 22:15:25.952458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6109349e1e'
down_revision: Union[str, None] = '999ccf5cba3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'original_filename')
    # ### end Alembic commands ###
