"""Add title field to Storage schema.

Revision ID: a9d8b686c874
Revises: 6ce246100fed
Create Date: 2025-06-21 22:18:41.634219

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9d8b686c874"
down_revision: Union[str, None] = "6ce246100fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storage",
        sa.Column("title", sa.String(), nullable=True, default="Untitled storage"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage", "title")
    # ### end Alembic commands ###
