"""Make book covers list non-nullable.

Revision ID: dcfff0dbc04d
Revises: 2a0f43ab7089
Create Date: 2025-06-14 01:03:22.909997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcfff0dbc04d'
down_revision: Union[str, None] = '2a0f43ab7089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'covers',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'covers',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               nullable=True)
    # ### end Alembic commands ###
